const ICONS = {
  skills: `<path d="M24 6 42 15 24 24 6 15Z"/><path d="M6 24l18 9 18-9"/><path d="M6 33l18 9 18-9"/>`,
  pause: `<rect x="7" y="7" width="34" height="34" rx="9"/><path d="M19 17v14M29 17v14"/>`,
  format: `<path d="M8 11h32M8 19h22M8 27h28M8 35h16"/><path d="M33 31l5 5-5 5"/>`,
  stopwatch: `<circle cx="24" cy="27" r="15"/><path d="M24 27v-8"/><path d="M19 5h10M24 5v7"/>`,
  pullRequest: `<circle cx="13" cy="11" r="4"/><circle cx="13" cy="37" r="4"/><circle cx="35" cy="37" r="4"/><path d="M13 15v18"/><path d="M35 33V20a6 6 0 0 0-6-6h-7"/><path d="M26 10l-4 4 4 4"/>`,
};

export const PROJECTS = [
  {
    repo: "qol-tools/qol-skills",
    text: "Claude Code and Codex skills that teach coding agents how qol is built, tested and released.",
    icon: ICONS.skills,
    accent: "violet",
    label: "Agent skills",
    chips: [{ label: "JavaScript", dot: "#f1e05a" }, { label: "Claude Code" }, { label: "Codex" }],
  },
  {
    repo: "qol-tools/pointz",
    text: "Flutter app for controlling your PC from your phone. It pairs with the PointZerver plugin.",
    mark: "pointz",
    accent: "green",
    label: "Android · iOS",
    chips: [{ label: "Dart", dot: "#00b4ab" }, { label: "Flutter" }],
  },
  {
    repo: "KMRH47/bt-quickie",
    text: "Quick Bluetooth device access from the Windows system tray.",
    mark: "bluetooth",
    accent: "blue",
    label: "Windows",
    chips: [{ label: "C#", dot: "#178600" }],
  },
  {
    repo: "KMRH47/paused-changelists",
    text: "IntelliJ IDEA plugin that shelves a changelist's changes while keeping the changelist visible.",
    icon: ICONS.pause,
    accent: "pink",
    label: "JetBrains Marketplace",
    chips: [{ label: "Kotlin", dot: "#a97bff" }, { label: "IntelliJ Platform" }],
  },
  {
    repo: "KMRH47/conditional-format",
    text: "VS Code extension that formats the selection, or the whole document when nothing is selected.",
    icon: ICONS.format,
    accent: "teal",
    label: "VS Code Marketplace",
    chips: [{ label: "TypeScript", dot: "#3178c6" }],
  },
  {
    repo: "KMRH47/windows-like-remap",
    text: "Hammerspoon configuration that makes macOS keyboard shortcuts feel like Windows.",
    mark: "key-remap",
    accent: "amber",
    label: "macOS",
    chips: [{ label: "Lua", dot: "#6a76e0" }, { label: "Hammerspoon" }],
  },
  {
    repo: "KMRH47/fast-youtrack",
    text: "Desktop utility for quick time tracking in YouTrack, with encrypted token storage.",
    icon: ICONS.stopwatch,
    accent: "green",
    label: "Windows · macOS · Linux",
    chips: [{ label: "Python", dot: "#3572a5" }],
  },
  {
    repo: "KMRH47/github-youtrack-time",
    text: "Browser extension that logs YouTrack time straight from GitHub pull requests.",
    icon: ICONS.pullRequest,
    accent: "violet",
    label: "Firefox · Chrome",
    chips: [{ label: "JavaScript", dot: "#f1e05a" }],
  },
];
